/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ActionEvent;
import java.io.File;
import java.awt.event.ActionListener;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Frame_Main extends javax.swing.JFrame {
    String nol_jam="";
    String nol_menit="";
    String nol_detik="";

    /**
     * Creates new form Frame_Main
     */
    public Frame_Main() throws SQLException {
        initComponents();
        selectData();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        Nis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        P = new javax.swing.JRadioButton();
        L = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        TmpLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TglLahir = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Tgl = new javax.swing.JLabel();
        Jam = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 80, 30);

        Nis.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        getContentPane().add(Nis);
        Nis.setBounds(40, 160, 220, 30);

        tblData.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NamaSiswa", "Tempat Lahir", "Tanggal Lahir", "Jenis Kel.", "Kelas", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 170, 650, 380);

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("DATA SISWA");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(80, 0, 100, 30);

        P.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(P);
        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel2.add(P);
        P.setBounds(90, 310, 60, 30);

        L.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(L);
        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel2.add(L);
        L.setBounds(20, 310, 110, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 280, 140, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Kelas");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 340, 100, 30);

        Kelas.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jPanel2.add(Kelas);
        Kelas.setBounds(20, 370, 220, 30);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 400, 100, 30);

        Email.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jPanel2.add(Email);
        Email.setBounds(20, 430, 220, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 460, 110, 30);

        Alamat.setColumns(20);
        Alamat.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        Alamat.setRows(5);
        jScrollPane2.setViewportView(Alamat);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 490, 220, 90);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Nama");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 100, 100, 30);

        Nama.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jPanel2.add(Nama);
        Nama.setBounds(20, 130, 220, 30);

        TmpLahir.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jPanel2.add(TmpLahir);
        TmpLahir.setBounds(20, 190, 220, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Lahir");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 220, 100, 30);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Tempat Lahir");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 160, 100, 30);
        jPanel2.add(TglLahir);
        TglLahir.setBounds(20, 250, 220, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 90, 260, 590);

        jPanel1.setBackground(new java.awt.Color(140, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bodoni Bk BT", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 229, 229));
        jLabel2.setText("The Real Informatics School");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 290, 20);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 640, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\TS.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 280, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 80);

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 160, 670, 400);

        jPanel4.setBackground(new java.awt.Color(229, 229, 229));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 198));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(460, 10, 80, 40);

        jButton5.setBackground(new java.awt.Color(213, 230, 255));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(350, 10, 80, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(240, 10, 80, 40);

        jButton3.setBackground(new java.awt.Color(255, 234, 204));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(130, 10, 80, 40);

        jButton2.setBackground(new java.awt.Color(200, 255, 200));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(20, 10, 80, 40);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(570, 10, 80, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(290, 90, 670, 60);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Nama");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 190, 100, 30);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(null);

        Tgl.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        Tgl.setForeground(new java.awt.Color(102, 102, 102));
        Tgl.setText("Tgl:");
        jPanel5.add(Tgl);
        Tgl.setBounds(10, 10, 140, 30);

        Jam.setBackground(new java.awt.Color(102, 102, 102));
        Jam.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        Jam.setForeground(new java.awt.Color(102, 102, 102));
        Jam.setText("Jam:");
        jPanel5.add(Jam);
        Jam.setBounds(10, 40, 130, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(830, 0, 140, 80);

        jLabel14.setFont(new java.awt.Font("Utsaah", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("SMK Telkom Malang 2017");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(470, 600, 350, 40);

        setSize(new java.awt.Dimension(984, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(TglLahir.getDate());
        String JK = "";
            if (L.isSelected())
            {
                JK = "L";
            }
            if (P.isSelected())
            {
                JK = "P";
            }
        
        if("".equals(Nis.getText()) || "".equals(Nama.getText()) || "".equals(tanggal) || "".equals(JK) || "".equals(Kelas.getText()) || "".equals(Alamat.getText()) || "".equals(TmpLahir.getText()) || "".equals(Email.getText()))
        {
            JOptionPane.showMessageDialog(this, "ANDA HARUS MELENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else
        { 
            String SQL = "UPDATE tb_siswa SET "
                    + "NamaSiswa='"+Nama.getText()+"', TempatLahir='"+TmpLahir.getText()+"', TanggalLahir='"+TglLahir.getDate()+"' "
                    + "JenisKelamin='"+JK+"', Kelas='"+Kelas.getText()+"', Email='"+Email.getText()+"' "
                    + "Alamat='"+Alamat.getText()+"' "
                    + "WHERE NIS='"+Nis.getText()+"'";          
            int status = KoneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIUPDATE", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
                try {
                    selectData();
                } catch (SQLException ex) {
                    Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIUPDATE", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(TglLahir.getDate());
        String JK = "";
            if (L.isSelected())
            {
                JK = "L";
            }
            if (P.isSelected())
            {
                JK = "P";
            }
        
        if("".equals(Nis.getText()) || "".equals(Nama.getText()) || "".equals(tanggal) || "".equals(JK) || "".equals(Kelas.getText()) || "".equals(Alamat.getText()) || "".equals(TmpLahir.getText()) || "".equals(Email.getText()))
        {
            JOptionPane.showMessageDialog(this, "ANDA HARUS MELENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else
        {
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat) "
                    + "VALUES('"+Nis.getText()+"','"+Nama.getText()+"','"+TmpLahir.getText()+"','"+TglLahir.getDate()+"',"
                    + "'"+JK+"','"+Kelas.getText()+"','"+Email.getText()+"','"+Alamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DITAMBAHKAN", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
                try {
                    selectData();
                } catch (SQLException ex) {
                    Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DITAMBAHKAN", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1)
        {
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIHAPUS", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIHAPUS", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }else
        {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin Anda hapus terlebih dahulu!", "ERROR!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Nama.setText("");
        Nis.setText("");
        TmpLahir.setText("");
        TglLahir.setDate(null);
        Kelas.setText("");
        buttonGroup1.clearSelection();
        Email.setText("");
        Alamat.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            selectData();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1)
        {
            Nis.setText(tblData.getValueAt(baris, 0).toString());
            Nama.setText(tblData.getValueAt(baris, 1).toString());
            TmpLahir.setText(tblData.getValueAt(baris, 2).toString());
            
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateformat = null;
            try{
                dateformat = date.parse(tblData.getValueAt(baris, 3).toString());
            } catch (ParseException ex)
            {
                
            }
            
            TglLahir.setDate(dateformat);
            
            if("Laki-laki".equals(tblData.getValueAt(baris, 4).toString()))
            {
                L.setSelected(true);
            }else
            {
                P.setSelected(true);
            }
            
            Kelas.setText(tblData.getValueAt(baris, 5).toString());
            Email.setText(tblData.getValueAt(baris, 6).toString());
            Alamat.setText(tblData.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch (java.awt.print.PrinterException e) {
            System.err.format("Can not print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frame_Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void setTanggal()
    {
        java.util.Date skg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        Tgl.setText(kal.format(skg));
    }
    
    public void setJam()
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours(); //get jam menit detik
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9)
                {
                    nol_jam = "0";
                }
                if(nilai_menit <= 9)
                {
                    nol_menit = "0";
                }
                if(nilai_detik <= 9)
                {
                    nol_detik = "0";
                }
                //string jam menit detik
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Jam.setText("Jam "+jam + ":" + menit + ":" + detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Jam;
    private javax.swing.JTextField Kelas;
    private javax.swing.JRadioButton L;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nis;
    private javax.swing.JRadioButton P;
    private javax.swing.JLabel Tgl;
    private com.toedter.calendar.JDateChooser TglLahir;
    private javax.swing.JTextField TmpLahir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void selectData() throws SQLException {
        String kolom[] = {"NIS","NamaSiswa","TempatLahir","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while(rs.next())
            {
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String TmpLahir = rs.getString(3);
                String TanggalLahir = rs.getString(4);
                String JenisKelamin = "";
                if("L".equals(rs.getString(5)))
                {
                    JenisKelamin = "Laki-laki";
                }else
                {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(6);
                String Email = rs.getString(7);
                String Alamat = rs.getString(8);
                String data[] = {NIS,NamaSiswa,TmpLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        }catch (SQLException ex)
        {
            Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
